language: python
python:
  - 2.6
  - 2.7
  - 3.4
env:
  - DJANGO_VERSION=1.4.20
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.8
  - DJANGO_VERSION=1.8.2
matrix:
  exclude:
    - python: 2.6
      env: DJANGO_VERSION=1.7.8
    - python: 2.6
      env: DJANGO_VERSION=1.8.2
    - python: 3.4
      env: DJANGO_VERSION=1.4.20
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r test_requirements.txt
script: coverage run --source='balancer' runtests.py
notifications:
  email: false
after_success:
  - coveralls
